name: Release

on: 
  push:
    tags:
    - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4.1.1

    - name: Set up Go
      uses: actions/setup-go@v5.0.0
      with:
        go-version: 1.22.0

    - name: Build for Linux
      run: cd src && GOOS=linux GOARCH=amd64 go build -o ../srenity_linux_amd64

    - name: Build for Windows
      run: cd src && GOOS=windows GOARCH=amd64 go build -o ../srenity_windows_amd64.exe

    - name: Build for macOS
      run: cd src && GOOS=darwin GOARCH=amd64 go build -o ../srenity_darwin_amd64

    - name: Build for Linux ARM
      run: cd src && GOOS=linux GOARCH=arm64 go build -o ../srenity_linux_arm64

    - name: Build for Windows ARM
      run: cd src && GOOS=windows GOARCH=arm64 go build -o ../srenity_windows_arm64.exe

    - name: Build for macOS ARM
      run: cd src && GOOS=darwin GOARCH=arm64 go build -o ../srenity_darwin_arm64

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.3.1
      with:
        name: srenity-artifacts
        path: srenity*
        if-no-files-found: error
        

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Download Release Artifacts
      uses: actions/download-artifact@v4
      with:
        name: srenity-artifacts

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: true

    - name: Upload Release Assets
      id: upload-release-assets
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: |
          srenity_linux_amd64
          srenity_windows_amd64.exe
          srenity_darwin_amd64
          srenity_linux_arm64
          srenity_windows_arm64.exe
          srenity_darwin_arm64
        asset_name: |
          srenity-linux_amd64-${{ github.event.release.tag_name }}
          srenity_windows_amd64-${{ github.event.release.tag_name }}.exe
          srenity_darwin_amd64-${{ github.event.release.tag_name }}
          srenity_linux_arm64-${{ github.event.release.tag_name }}
          srenity_windows_arm64-${{ github.event.release.tag_name }}.exe
          srenity_darwin_arm64-${{ github.event.release.tag_name }}
        asset_content_type: application/octet-stream
