version: '3'

services:
  srenity-influx:
    image: influxdb:1.8
    container_name: srenity-influx
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=testdb
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=adminpassword
      - INFLUXDB_USER=user
      - INFLUXDB_USER_PASSWORD=userpassword
